### ISSUE TITLE
Document Creation

### ISSUE THREAD

**Issue by MJCD** [secops-space/secops.space#17]
- [/LICENCE.md] represents an agreement between 'secops' and 'the user'
- [/Members.md] represents an agreement between 'secops' and 'the member'
- [/Federators.md] represents an agreement between 'secops' and 'federated servers' 

- [/README.md] should be a fairly indepth document that matures over time. To start with, explain the concept. Link the site, irc details (also ##secops.space on freenode), put a section in with the header of "Team" - each person signing on with the dev team will need to add themselves to this and write a short bio.

**Comment by ctrlaltdev** [comment]
LICENSE.md (or LICENCE.md) is by convention the license under which the code in the repo is available.

Regarding license, members and federators, this is a community, not a business, I don't think an agreement between secops.space (that is not a legal entity) and the users or the members is needed.

Moreover, markdown files would be for the use of the code and this repo, not for the website and the community.

The information you list for README would rather have a place in the about page of the website, README, by convention, usually quickly presents the project (and usually links to outside resources, i.e. the website and IRC) and explains how to use the code.

Overall, I think there's a confusion on what appears on the website, and what is for github.

CONTRIBUTING.md could be created explaining on how to be a contributor to this repo / IRC / community.
CONTRIBUTORS.md could list the contributors (of any type, not only devs), if we want to do that.
Otherwise, it is common practice to list them at the end of the readme, with only github handle and avatar, and sometimes the category (code, infra, etc.)

**Comment by jxhn** [comment]
@ctrlaltdev Has really hit the nail on the head here. We've added a license to the repo, stipulating MIT and the `CONTRIBUTING.md` is in PR at the moment. That should be enough for the time being. The `README.md` should really just explain how to get the site up and running and perhaps include a link to the `CONTRIBUTING.md` once it's merged.

I move that we close this issue as the information around the federation, users and staff are all going to go on the site in the about tree/page.
